version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: adm_discord
    ports: 
      - "5432:5432"
    
  discord_app:
    build: "./bot"
    container_name: "discord_app"
    restart: always
    volumes: 
      - "./bot:/app"
    depends_on:
      - database

